title: John Amaka
logo: https://www.credly.com/badges/4f4a1413-6db1-492c-b6ff-2668f69a0b8d/public_url
description: >
  A professional with a background in Project Management seeking to transition into data science having garnered skills towards data analysis and engineering via self-study.

  <div data-iframe-width="150" data-iframe-height="270" data-share-badge-id="4f4a1413-6db1-492c-b6ff-2668f69a0b8d" data-share-badge-host="https://www.credly.com"></div><script type="text/javascript" async src="//cdn.credly.com/assets/utilities/embed.js"></script>
  <div data-iframe-width="150" data-iframe-height="270" data-share-badge-id="35d94925-ad79-45ff-a0da-7bb31447ad48" data-share-badge-host="https://www.credly.com"></div><script type="text/javascript" async src="//cdn.credly.com/assets/utilities/embed.js"></script>
  <div data-iframe-width="150" data-iframe-height="270" data-share-badge-id="0772e40d-67fa-4747-bc10-88de0fde8dcc" data-share-badge-host="https://www.credly.com"></div><script type="text/javascript" async src="//cdn.credly.com/assets/utilities/embed.js"></script>

show_downloads: True
theme: jekyll-theme-minimal
