title: John Amaka
logo: https://github.com/John-AE/portfolio/raw/main/profile.jpg
description: >
  <div class="badge-container" data-iframe-width="150" data-iframe-height="270" data-share-badge-id="35d94925-ad79-45ff-a0da-7bb31447ad48" data-share-badge-host="https://www.credly.com"></div><script type="text/javascript" async src="//cdn.credly.com/assets/utilities/embed.js"></script>

show_downloads: True
theme: jekyll-theme-minimal
