title: John Amaka
#logo:
description: A professional with a background in Project Management seeking to transition into data science having garnered skills towards data analysis and engineering via self-study
show_downloads: True
theme: jekyll-theme-minimal
