title: John Amaka
logo: https://www.credly.com/badges/4f4a1413-6db1-492c-b6ff-2668f69a0b8d/public_url
description: A professional with a background in Project Management seeking to transition into data science having garnered skills towards data analysis and engineering via self-study
show_downloads: True
theme: jekyll-theme-minimal
